swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /conocimiento_idioma/:
    get:
      tags:
      - conocimiento_idioma
      description: get ConocimientoIdioma
      operationId: ConocimientoIdiomaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConocimientoIdioma'
        "404":
          description: not found resource
    post:
      tags:
      - conocimiento_idioma
      description: create ConocimientoIdioma
      operationId: ConocimientoIdiomaController.Post
      parameters:
      - in: body
        name: body
        description: body for ConocimientoIdioma content
        required: true
        schema:
          $ref: '#/definitions/models.ConocimientoIdioma'
      responses:
        "201":
          description: '{int} models.ConocimientoIdioma'
        "400":
          description: the request contains incorrect syntax
  /conocimiento_idioma/{id}:
    get:
      tags:
      - conocimiento_idioma
      description: get ConocimientoIdioma by id
      operationId: ConocimientoIdiomaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConocimientoIdioma'
        "404":
          description: not found resource
    put:
      tags:
      - conocimiento_idioma
      description: update the ConocimientoIdioma
      operationId: ConocimientoIdiomaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for ConocimientoIdioma content
        required: true
        schema:
          $ref: '#/definitions/models.ConocimientoIdioma'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ConocimientoIdioma'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - conocimiento_idioma
      description: delete the ConocimientoIdioma
      operationId: ConocimientoIdiomaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /idioma/:
    get:
      tags:
      - idioma
      description: get Idioma
      operationId: IdiomaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Idioma'
        "404":
          description: not found resource
    post:
      tags:
      - idioma
      description: create Idioma
      operationId: IdiomaController.Post
      parameters:
      - in: body
        name: body
        description: body for Idioma content
        required: true
        schema:
          $ref: '#/definitions/models.Idioma'
      responses:
        "201":
          description: '{int} models.Idioma'
        "400":
          description: the request contains incorrect syntax
  /idioma/{id}:
    get:
      tags:
      - idioma
      description: get Idioma by id
      operationId: IdiomaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Idioma'
        "404":
          description: not found resource
    put:
      tags:
      - idioma
      description: update the Idioma
      operationId: IdiomaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Idioma content
        required: true
        schema:
          $ref: '#/definitions/models.Idioma'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Idioma'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - idioma
      description: delete the Idioma
      operationId: IdiomaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /nivel/:
    get:
      tags:
      - nivel
      description: get Nivel
      operationId: NivelController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Nivel'
        "404":
          description: not found resource
    post:
      tags:
      - nivel
      description: create Nivel
      operationId: NivelController.Post
      parameters:
      - in: body
        name: body
        description: body for Nivel content
        required: true
        schema:
          $ref: '#/definitions/models.Nivel'
      responses:
        "201":
          description: '{int} models.Nivel'
        "400":
          description: the request contains incorrect syntax
  /nivel/{id}:
    get:
      tags:
      - nivel
      description: get Nivel by id
      operationId: NivelController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Nivel'
        "404":
          description: not found resource
    put:
      tags:
      - nivel
      description: update the Nivel
      operationId: NivelController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Nivel content
        required: true
        schema:
          $ref: '#/definitions/models.Nivel'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Nivel'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - nivel
      description: delete the Nivel
      operationId: NivelController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /soporte_conocimiento_idioma/:
    get:
      tags:
      - soporte_conocimiento_idioma
      description: get SoporteConocimientoIdioma
      operationId: SoporteConocimientoIdiomaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SoporteConocimientoIdioma'
        "404":
          description: not found resource
    post:
      tags:
      - soporte_conocimiento_idioma
      description: create SoporteConocimientoIdioma
      operationId: SoporteConocimientoIdiomaController.Post
      parameters:
      - in: body
        name: body
        description: body for SoporteConocimientoIdioma content
        required: true
        schema:
          $ref: '#/definitions/models.SoporteConocimientoIdioma'
      responses:
        "201":
          description: '{int} models.SoporteConocimientoIdioma'
        "400":
          description: the request contains incorrect syntax
  /soporte_conocimiento_idioma/{id}:
    get:
      tags:
      - soporte_conocimiento_idioma
      description: get SoporteConocimientoIdioma by id
      operationId: SoporteConocimientoIdiomaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SoporteConocimientoIdioma'
        "404":
          description: not found resource
    put:
      tags:
      - soporte_conocimiento_idioma
      description: update the SoporteConocimientoIdioma
      operationId: SoporteConocimientoIdiomaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for SoporteConocimientoIdioma content
        required: true
        schema:
          $ref: '#/definitions/models.SoporteConocimientoIdioma'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SoporteConocimientoIdioma'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - soporte_conocimiento_idioma
      description: delete the SoporteConocimientoIdioma
      operationId: SoporteConocimientoIdiomaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
  /valor_nivel_idioma/:
    get:
      tags:
      - valor_nivel_idioma
      description: get ValorNivelIdioma
      operationId: ValorNivelIdiomaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ValorNivelIdioma'
        "404":
          description: not found resource
    post:
      tags:
      - valor_nivel_idioma
      description: create ValorNivelIdioma
      operationId: ValorNivelIdiomaController.Post
      parameters:
      - in: body
        name: body
        description: body for ValorNivelIdioma content
        required: true
        schema:
          $ref: '#/definitions/models.ValorNivelIdioma'
      responses:
        "201":
          description: '{int} models.ValorNivelIdioma'
        "400":
          description: the request contains incorrect syntax
  /valor_nivel_idioma/{id}:
    get:
      tags:
      - valor_nivel_idioma
      description: get ValorNivelIdioma by id
      operationId: ValorNivelIdiomaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ValorNivelIdioma'
        "404":
          description: not found resource
    put:
      tags:
      - valor_nivel_idioma
      description: update the ValorNivelIdioma
      operationId: ValorNivelIdiomaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for ValorNivelIdioma content
        required: true
        schema:
          $ref: '#/definitions/models.ValorNivelIdioma'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ValorNivelIdioma'
        "400":
          description: the request contains incorrect syntax
    delete:
      tags:
      - valor_nivel_idioma
      description: delete the ValorNivelIdioma
      operationId: ValorNivelIdiomaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "404":
          description: not found resource
definitions:
  models.ConocimientoIdioma:
    title: ConocimientoIdioma
    type: object
    properties:
      FechaCreacion:
        type: string
        format: string
      FechaModificacion:
        type: string
        format: string
      Id:
        type: integer
        format: int64
      IdiomaId:
        $ref: '#/definitions/models.Idioma'
      Nativo:
        type: boolean
      NivelEscribeId:
        $ref: '#/definitions/models.ValorNivelIdioma'
      NivelEscuchaId:
        $ref: '#/definitions/models.ValorNivelIdioma'
      NivelHablaId:
        $ref: '#/definitions/models.ValorNivelIdioma'
      NivelId:
        $ref: '#/definitions/models.Nivel'
      NivelLeeId:
        $ref: '#/definitions/models.ValorNivelIdioma'
      TercerosId:
        type: integer
        format: int64
  models.Idioma:
    title: Idioma
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      FechaCreacion:
        type: string
        format: string
      FechaModificacion:
        type: string
        format: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.Nivel:
    title: Nivel
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      FechaCreacion:
        type: string
        format: string
      FechaModificacion:
        type: string
        format: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.SoporteConocimientoIdioma:
    title: SoporteConocimientoIdioma
    type: object
    properties:
      ConocimientoIdiomaId:
        $ref: '#/definitions/models.ConocimientoIdioma'
      Descripcion:
        type: string
      DocumentoId:
        type: integer
        format: int64
      FechaCreacion:
        type: string
        format: string
      FechaModificacion:
        type: string
        format: string
      Id:
        type: integer
        format: int64
      TercerosId:
        type: integer
        format: int64
  models.ValorNivelIdioma:
    title: ValorNivelIdioma
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      FechaCreacion:
        type: string
        format: string
      FechaModificacion:
        type: string
        format: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
tags:
- name: idioma
  description: |
    IdiomaController operations for Idioma
- name: nivel
  description: |
    NivelController operations for Nivel
- name: valor_nivel_idioma
  description: |
    ValorNivelIdiomaController operations for ValorNivelIdioma
- name: conocimiento_idioma
  description: |
    ConocimientoIdiomaController operations for ConocimientoIdioma
- name: soporte_conocimiento_idioma
  description: |
    SoporteConocimientoIdiomaController operations for SoporteConocimientoIdioma
